apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-07-03T16:30:26Z"
  generation: 1
  labels:
    app: translate-web
  name: translate-web
  namespace: default
  resourceVersion: "20607"
  selfLink: /apis/apps/v1/namespaces/default/deployments/translate-web
  uid: 74a7302e-b570-474a-9f68-c14bf2caa8ed
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: translate-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: translate-web
    spec:
      containers:
      - image: caprilespe/translate-web:v1
        imagePullPolicy: IfNotPresent
        name: translate-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-07-03T16:30:28Z"
    lastUpdateTime: "2021-07-03T16:30:28Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-07-03T16:30:26Z"
    lastUpdateTime: "2021-07-03T16:30:28Z"
    message: ReplicaSet "translate-web-7b9c885757" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
