apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-07-03T16:39:05Z"
  labels:
    app: translate-web
  name: translate-web
  namespace: default
  resourceVersion: "20978"
  selfLink: /api/v1/namespaces/default/services/translate-web
  uid: 49fa5c62-cdb9-45b2-9bb4-9636dd1c8f1f
spec:
  clusterIP: 10.102.161.180
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31815
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: translate-web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
